

package main

import "errors"
import "fmt"
import "math"

func Sqrt(value float64)(float64, error) {
   if(value < 0){
      return 0, errors.New("MATH ERROR: negative number passed to Sqrt function")
   }
   return math.Sqrt(value), nil
}
func main() {
   result, err:= Sqrt(-1)
   fmt.Println("Given num is -1 then:")
   if err != nil {
      fmt.Println(err)
   } else {
      fmt.Println("square root is:",result)
   }
   fmt.Println("Given num is 9 then:")
   result, err = Sqrt(9)

   if err != nil {
      fmt.Println(err)
   } else {
      fmt.Println("square root is:",result)

   }

fmt.Println("Given num is 0 then:")
 result, err = Sqrt(0)
   if err != nil {
      fmt.Println(err)
   } else {
      fmt.Println(result)
   }
}

OUTPUT:-

Given num is -1 then:
MATH ERROR: negative number passed to Sqrt function
Given num is 9 then:
square root is: 3
Given num is 0 then:
0